### PR TITLE
5.5.1 release preview

### PR DESCRIPTION
**Pull request by Cryptkeeper**
**5.5.1** *(June 8 2020)*
- New tooltip hover design on the historical graph. It will highlight the server closest to your cursor.
- Historical graph is now limited to 10,000 increments on the Y axis. This prevents servers with over 100,000 players forcing the graph into 100,000 increments.
- Replaces manual string concats with template literals.
- Updated various dependencies.

Merge target date: ~June 9th 2020~ June 10th 2020

### CODE REVIEW

**Comment by Cryptkeeper** [comment]
Going to make some further tooltip tweaks, the closest server hover behavior is very glitchy...

**Comment by hugmanrique** [comment]
Re cursor offset: I don’t know if the +20 offset is browser dependent, maybe this has something to do with it? https://github.com/leeoniya/uPlot/blob/88cbc2cd3f26e72f97bbe6b373267f1e2b42857f/src/opts.js#L321

**Comment by Cryptkeeper** [comment]
Strange, I'll dig into it more. Thanks for the mention. I'm going to close this release since it seems like the uPlot update broke some rendering and I'll need to investigate more anyways.

**Comment by Cryptkeeper** [comment]
I've opened https://github.com/leeoniya/uPlot/issues/257 to resolve a TypeError occurring on freshly booted Minetrack 5.5.1 instances. I've temporarily downgraded uPlot 1.0.10=>1.0.9 to avoid this bug in the meanwhile (it has still been upgraded from 1.0.8).

I'm following up on https://github.com/leeoniya/uPlot/issues/254 with the issues related to cursor selection.

**Comment by Cryptkeeper** [comment]
The cursor issue has been fixed. Given that uPlot is currently stable on 1.0.9, I'm going to stage this for release while the uPlot 1.0.10 changes get tested for the next Minetrack release.

**Comment by Cryptkeeper** [comment]
Closing in favor of https://github.com/Cryptkeeper/Minetrack/pull/181

**Pull request closed without merging**
