### PR TITLE
Change lifeboat to play.lbsg.net

### PR DESCRIPTION
**Pull request by Notoh**
Fixes issue #72 where it will not ping correctly.

### CODE REVIEW

**Comment by hugmanrique** [comment]
In the past the IP was `play.lbsg.net` and it gave the same pinging issues as the stats IP does.

**Comment by Classic36MC** [comment]
I currently have both running on my fork of Minetrack - stats.lbsg.net doesn't ping at all, yet play.lbsg.net does.

http://imgur.com/a/3d2Bq

**Comment by hugmanrique** [comment]
Yeah, but you can see those ping rejections every few seconds, that's why it got changed originally

**Comment by Classic36MC** [comment]
Eh, occasional ping rejections are better than not pinging all together :P

**Comment by Classic36MC** [comment]
Nice :)

**Pull request merged**
