### PR TITLE
Design Tweaks

### PR DESCRIPTION
**Pull request by GingerGeek**
THIS PR IS A WORK IN PROGRESS

The main issue I have with MineTrack at the moment is that it's very "big" and contains many hardcoded widths etc, this PR hopes to fix that

- Make stuff generally smaller
- Remove most hard-coded values
- 3 servers a row
- Add small header

### CODE REVIEW

**Comment by GingerGeek** [comment]
Live version of this can be found at http://minetrack.gingergeek.co.uk/ - feedback appreciated

**Comment by theminecoder** [comment]
:+1:

**Comment by GingerGeek** [comment]
I've more or less done everything I wanted to add now @Cryptkeeper

**Comment by GingerGeek** [comment]
Ok so fixed some broken mobile stuff i think @Cryptkeeper - this is more or less ready for your feedback

**Comment by Cryptkeeper** [comment]
I'll take a look at this tomorrow

**Comment by GingerGeek** [comment]
@Cryptkeeper I've updated this to support Minetrack 2.0.0 you can see the result here https://minetrack.gingergeek.co.uk/

**Comment by Cryptkeeper** [comment]
I'll dissect this request soon, dealing with a few things internally at the moment.

**Comment by GingerGeek** [comment]
If you want me to do anything then just let me know :)

**Comment by NAAVOO** [comment]
Hey @Cryptkeeper, wake up and merge this :smile:

**Comment by GingerGeek** [comment]
I've made it so it's mergeable however I'm not yet satisifed with the mess of the commit this will cause so I'm going to try and reduce the diff on it a bit

**Comment by GingerGeek** [comment]
This is probably the best I'm going to get it, the diff is not as tidy as I would have liked but the base has moved so much since I opened this PR I had little choice.

This isn't yet live on minetrack.gingergeek.co.uk but hopefully will be in the next day or so or by the time you read this.

**Comment by GingerGeek** [comment]
Do you not want any of this then?

**Comment by NAAVOO** [comment]
Hmm. 
I really like this PR, but @Cryptkeeper owns this project, so its his decision.

**Pull request closed without merging**
