### PR TITLE
Fix XSS by parsing player counts as raw data and validating favicon URIs

### LINKED ISSUE #115: Cross-site scripting vulnerability
A server can return a maliciously crafted Server Ping Response (https://wiki.vg/Server_List_Ping#Response).
I was able to replace the online players value with `"<script>alert('XSS')</script>"` and have this code get executed.

### PR DESCRIPTION
**Pull request by hugmanrique**
Currently the server accepts any kind of response from the server ping. This commit `parseInt`s the `version.protocol`, `players.max` and `players.online` fields ([Reference](https://wiki.vg/Server_List_Ping#Response)). The `favicon` field doesn't need to be escaped as it is currently passed to the DOM via a jQuery `.attr('src', favicon)` call (which is [safe from XSS](https://security.stackexchange.com/questions/160175/is-there-a-possability-to-inject-xss-into-the-jquery-attr-function)).

A better solution would be to move this fix up to the `mcping` repo, but this was a rather quick and temp fix.

Fixes #115 (@LXGaming, do you mind testing your attack against this branch?)

### CODE REVIEW

**Comment by LXGaming** [comment]
During testing I've found more issues:
- If the favicon value is a URL then the end client will actually send a GET request to the URL every update.
- The favicon image size is not enforced, I can return a 1920x1080 resolution image and break the entire site.

players.online has been fixed.

I'm using https://github.com/lolnetnz/Void in order to create custom server ping responses.

**Comment by hugmanrique** [comment]
Alright, this should now block any favicon URI that doesn't start with `data:image` and prevent large images from breaking the site. I feel like blocking favicons with different dimensions, albeit not following the official Minecraft protocol, would be too strict and would require a rewrite of the jQuery element to a native `Image` instance where we could check the image dimensions.

**Comment by LXGaming** [comment]
Retested and can confirm issues have now been fixed.

Thanks @hugmanrique

**Comment by hugmanrique** [comment]
Bump @Cryptkeeper

**Comment by Cryptkeeper** [comment]
Thanks for the patch! Sorry merging it took so long :heart:

**Pull request merged**
