### PR TITLE
Add Minehut

### PR DESCRIPTION
**Pull request by MDMCK10**
Add Minehut (https://minehut.com)

### CODE REVIEW

**Comment by MDMCK10** [comment]
@Cryptkeeper

**Comment by MDMCK10** [comment]
@Cryptkeeper

**Comment by MDMCK10** [comment]
@Cryptkeeper

**Comment by MiniDigger** [comment]
it doesnt look like crypt has the intention of pulling this. dont be rude and ping him all the time.

**Comment by MDMCK10** [comment]
@MiniDigger i don't think that i'm pinging him "all the time", considering the last time i did before this one was 3 months + 24 days ago

**Comment by Cryptkeeper** [comment]
Sorry for the delay. I'm closing all PRs looking to add servers to the "official" (https://minetrack.me) pages. 

I'm barely maintaining the site as is, and I'm not interested in add/removing/tweaking servers (and the arguments that come with) since I'm not involved in the Minecraft ecosystem anymore. Short of any of the currently tracked servers closing down, I don't expect any further changes to the server list.

Please fork (or build a competitor to) Minetrack and add your desired servers there. Minetrack has lived a long, happy life but I think it's time for better tools :)

**Comment by MDMCK10** [comment]
welp :(

**Pull request closed without merging**
