### PR TITLE
Add link to china servers on Pocket edition page

### PR DESCRIPTION
**Pull request by Notoh**
This change just adds the link to the china servers on the pocket edition page like it is for PC.

### CODE REVIEW

**Comment by hugmanrique** [comment]
It seems like Crypt didn't push his code and he didn't create the new China branch, so this PR is going to conflict once he pushes.

**Comment by Notoh** [comment]
Thing is, even on https://pe.minetrack.com it doesn't show the link to china servers at the top like it does on PC suggesting it will probably not.

**Comment by Notoh** [comment]
My bad misclicked on the closed/opened.

**Comment by Cryptkeeper** [comment]
I've pushed my updated prod/prod-pocket and the new prod-china branches with the updated header links. Thanks for the heads up!

**Pull request closed without merging**
