### PR TITLE
configurable ping fail logs

### PR DESCRIPTION
**Pull request by blockparole**
I had to add this because after testing Minetrack for a few days i had a 150mb log file. Might be a useful option to someone else too so i do pr.

_if merge, pls squash, i had to do some quick fixes_

### CODE REVIEW

**Comment by blockparole** [comment]
maybe `logFailedPings` should be renamed to `logFailedPingsToLogFile` to make it more clear what the option does.

**Comment by Cryptkeeper** [comment]
If you swap the `logFailedPings` value to true by default (and subsequently make the code usage treat an undefined value as true), then I'm happy to merge it. I want to avoid changing default behavior for existing installations.

**Comment by blockparole** [comment]
requests implemented. i would really think about if its necessary to log failed pings in such a frequency it can grow a log file to > 100mb in under a week and default it to false but its your decision to make.

**Comment by Cryptkeeper** [comment]
I agree with your issue, I just want to avoid changing the default and confusing current users.

The logging library (winston) offers "maxsize" & "maxFiles" params to prevent exceedingly large log files (and subsequently, when rolling over, a limited amount of files). These will likely be a better solution to your problem than specifically just avoiding failure logging: https://github.com/winstonjs/winston/blob/2.x/docs/transports.md#file-transport

**Pull request merged**
